name: Server Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis-cache:
        image: redis:alpine
        ports:
          - 13000:6379
      redis-queue:
        image: redis:alpine
        ports:
          - 11000:6379
      redis-socketio:
        image: redis:alpine
        ports:
          - 12000:6379
      mariadb:
        image: mariadb:10.6
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: _tmp
          MYSQL_USER: root
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          check-latest: true

      - name: Cache bench folder
        uses: actions/cache@v4
        with:
          path: ~/bench-cache
          key: ${{ runner.os }}-bench-cache-v2

      - name: Install bench CLI
        run: |
          python -m pip install --upgrade pip
          pip install frappe-bench
          bench --version

      - name: bench init (reuse cache if present)
        run: |
          set -eux
          if [ -f "$HOME/bench-cache/bench.tgz" ]; then
            (cd && tar xzf "$HOME/bench-cache/bench.tgz")
            bench --version
            bench setup env --python "$(which python)"
          else
            bench init "$HOME/frappe-bench" \
              --skip-redis-config-generation \
              --skip-assets \
              --frappe-branch version-15 \
              --python "$(which python)"
            mkdir -p "$HOME/bench-cache"
            (cd && tar czf "$HOME/bench-cache/bench.tgz" frappe-bench)
          fi

      - name: Add geo_extension app to bench
        working-directory: /home/runner/frappe-bench
        env:
          GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
        run: |
          # Use the checked-out workspace as the app source
          bench get-app geo_extension "$GITHUB_WORKSPACE"

      - name: Create bench site
        working-directory: /home/runner/frappe-bench
        env:
          DB_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
        run: |
          bench new-site frappe.local \
            --db-host 127.0.0.1 \
            --mariadb-root-password root \
            --admin-password admin \
            --no-mariadb-socket

      - name: Install geo_extension app
        working-directory: /home/runner/frappe-bench
        run: bench --site frappe.local install-app geo_extension

      - name: Setup requirements (dev)
        working-directory: /home/runner/frappe-bench
        run: bench setup requirements --dev

      - name: Allow tests
        working-directory: /home/runner/frappe-bench
        run: bench --site frappe.local set-config allow_tests true

      - name: Build assets (site)
        working-directory: /home/runner/frappe-bench
        run: bench --site frappe.local build

      - name: Run tests
        working-directory: /home/runner/frappe-bench
        env:
          CI: "1"
        run: bench --site frappe.local run-tests --app geo_extension
