name: Generate Semantic Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Avoid looping when the bot pushes the version bump
    if: "!startsWith(github.event.head_commit.message, 'chore(release)')"

    steps:
      - name: Checkout Entire Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup dependencies
        run: |
          npm install @semantic-release/git @semantic-release/exec --no-save
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: "PR Bot"
          GIT_AUTHOR_EMAIL: "sudopotito@gmail.com"
          GIT_COMMITTER_NAME: "PR Bot"
          GIT_COMMITTER_EMAIL: "sudopotito@gmail.com"
        run: npx semantic-release